# Package name
package: etherlabmaster

# Project name for human-readable output
projectName: IgH EtherCAT Master

# Cloudsmith repo namespace (org name); also may be set in $CLOUDSMITH_NAMESPACE
cloudsmith_repo_namespace: zultron
# Cloudsmith repo slug, if not the same as `package`
# cloudsmith_repo_slug: etherlabmaster
cloudsmith_repo_slug: etherlabmaster-test

matrix:
  # List of Debian and Ubuntu OS version configuration data
  - baseImage: debian:bookworm
    # When EOL? https://www.debian.org/releases/bookworm/
    codename: Bookworm
    vendor: Debian
    release: 12
    architectures:
      - amd64
      - arm64
      - armhf
  - baseImage: debian:bullseye
    # When EOL? https://www.debian.org/releases/bullseye/
    codename: Bullseye
    vendor: Debian
    release: 11
    architectures:
      - amd64
      - arm64
      - armhf
  - baseImage: debian:buster
    # EOL 2024-07-01 https://www.debian.org/releases/buster/
    codename: Buster
    vendor: Debian
    release: 10
    architectures:
      - amd64
      - arm64
      - armhf
  - baseImage: ubuntu:jammy
    # EOL 04-2032  https://ubuntu.com/about/release-cycle
    codename: Jammy
    vendor: Ubuntu
    release: 22.04
    architectures:
      - amd64
      - arm64
      - armhf
  - baseImage: ubuntu:focal
    # EOL 04-2030  https://ubuntu.com/about/release-cycle
    codename: Focal
    vendor: Ubuntu
    release: 20.04
    architectures:
      - amd64
      - arm64
      - armhf
  - baseImage: ubuntu:trusty
    # EOL 04-2024  https://ubuntu.com/about/release-cycle
    codename: Trusty
    vendor: Ubuntu
    release: 14.04
    architectures:
      - amd64
